steps:
  # Auth
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 
      'northamerica-northeast1-docker.pkg.dev/sleepr-460214/auth/production', 
      '-f',
      'apps/auth/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'northamerica-northeast1-docker.pkg.dev/sleepr-460214/auth/production'
    ]
  # Notifications
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 
      'northamerica-northeast1-docker.pkg.dev/sleepr-460214/notifications/production', 
      '-f',
      'apps/notifications/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'northamerica-northeast1-docker.pkg.dev/sleepr-460214/notifications/production'
    ]
  # Payments
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 
      'northamerica-northeast1-docker.pkg.dev/sleepr-460214/payments/production', 
      '-f',
      'apps/payments/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'northamerica-northeast1-docker.pkg.dev/sleepr-460214/payments/production'
    ]
  # Reservations
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 
      'northamerica-northeast1-docker.pkg.dev/sleepr-460214/reservations/production', 
      '-f',
      'apps/reservations/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'northamerica-northeast1-docker.pkg.dev/sleepr-460214/reservations/production'
    ]

logsBucket: 'gs://sleepr-460214-cloudbuild-logs'